version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2.11-fpm


    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "symfony_project/composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: cd symfony_project && composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "symfony_project/composer.json" }}

      # run tests!
      - run: chmod +x symfony_project/bin/phpunit
      - run: cd symfony_project && bin/phpunit